name: watchyy
description: "Watchyy app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.2 <3.33.0"


dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_reactive_ble: ^5.4.0
  go_router: ^14.1.3
  hooks_riverpod: ^2.5.1
  http: ^1.2.2
  icons_plus: ^5.0.0
  intl: ^0.20.2
  meta: ^1.15.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  riverpod: ^2.5.1
  sentry_flutter: ^8.3.0
  shared_preferences: ^2.2.3
  slang: ^3.31.0
  slang_flutter: ^3.31.0
  url_launcher: ^6.3.0

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  leancode_lint: ^17.0.0

flutter:
  uses-material-design: true